### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by ghost** [Noah-Huppert/Leap-Motion#2]
Hi Noah, 

I received two errors:
Exception in thread "main" java.lang.Error: Unresolved compilation problems:
ScreenList cannot be resolved to a type
The method calibratedScreens() is undefined for the type Controller
Screen cannot be resolved to a type

What would i be missing?

Kindest, 

neil

**Comment by catvec** [comment]
When I uploaded this code I forgot to upload the Manifest. I will be uploading a fully packed executable .jar of this program after Midterms are over. As for the ScreenList Issue and the calibratedScreens() issue, Have you calibrated your Leap and checked the calibration in the visualizer by pressing b?

**Comment by ghost** [comment]
I just calibrated my LEAP and I still get the same error when I try to run the code in eclipse.  The only thing I modified was the package name...just removed that line of code all together.

**Comment by ghost** [comment]
![Screen Shot 2013-01-24 at 5 21 57 PM](https://f.cloud.github.com/assets/3374058/95750/de3a6600-667c-11e2-8c53-b7eeffe4a7b7.png)

**Comment by catvec** [comment]
That might be your problem. Put in package com.NoahHuppert.LeapMotion.Mouse;
on the top line.

Noah Huppert

**Comment by ghost** [comment]
![Screen Shot 2013-01-24 at 5 25 46 PM](https://f.cloud.github.com/assets/3374058/95766/6ea6ded0-667d-11e2-92c4-f19f5edc6fdd.png)

Just included the package information and still the same problem.  what does the package statement actually import?

**Comment by catvec** [comment]
Can you please provide a screenshot of the whole window. I think I might know the problem but I want to double check.

**Comment by ghost** [comment]
![Screen Shot 2013-01-24 at 5 29 06 PM](https://f.cloud.github.com/assets/3374058/95777/ef17f1c6-667d-11e2-9c79-26bff93924c5.png)

yup, here is the whole window

**Comment by catvec** [comment]
Ok This will fix one problem maybe two. Right click on the Default package in your package explorer go to refractor and hit rename. Rename it com.NoahHuppert.LeapMotion.Mouse

**Comment by catvec** [comment]
The only other thing I can think of is the fact that you are running this on a mac. I am going to look at the Leap SKD documentation and see if those commands differ.

**Comment by ghost** [comment]
ok, refactor->rename fixed the package declaration statement but not the screenlist can not be resolved to a type and method calibrated screen is undefined for Controller errors.  
I am running on a Macbook pro

**Comment by catvec** [comment]
There are a couple things you can try to do. Go to the problems tab and right click on the errors and see if there are any quick fixes. The fact that I have been unable to replicate this error tells be this might have to do with the fact that it is running on a mac. When I looked through the API Reference I did not see anything that should change between Mac and Windows. Once Midterms are over I will have a little bit more time to look at this. For now just wait until I find time to export it to a executable jar.

**Comment by ghost** [comment]
the problem is that I don't have the screenlist class or the calibratedSCreens class in my referenced LeapJava.jar
![Screen Shot 2013-01-24 at 7 46 02 PM](https://f.cloud.github.com/assets/3374058/96118/02df0b1e-6691-11e2-83b4-3c598c1a7fbd.png)

**Comment by catvec** [comment]
Does your leap visualizer look sort of look like this when you press b(screen(s) might be different. If they do then I will look at this tomorrow with a fresh mind.
![Capture](https://f.cloud.github.com/assets/3323504/96143/aaf3a638-6692-11e2-863a-1fae4dd213ac.PNG)

**Comment by ghost** [comment]
Noah! I got it to work.  It had to do with not having the right native libraries pointed to when I setup the project. I made a stupid error on my part probably by only copying a few of the native libraries which the Leap website mentioned on their website.  I copied Leapjava.jar, lib_leapjavadylib, libleap.dylip to their own folder on my desktop. I then pointed the eclipse native library path to that new folder and that's why I think I missed something.   I just ran it and i was able to control the mouse pointer.  The only problem is that mouse pointer is very hard to control to say the least.  I think I have to recalibrate the device to look like the screenshot you posted.  by the way, what is the second box floating in the upper right hand corner? I don't have that one.  and my core box looks way different.  It's half across the Y plane and half across the bottom X plane.

**Comment by catvec** [comment]
Great! The Second box is my second screen that I have connected via VGA. As for the pointing it is a little odd. point with one finger, then when you are hovering over something you want to click you can do one of two things. The first thing you can do is move your thumb into the view of the leap. The second thing you can do to click is quickly poke another finger in for as little as possible. You can also comment the circled red section out and uncomment the blue section to get thee "jab" to click method. This is were you point and then "jab" at the screen to click. The circled black number is the Sensitivity of the jab. The higher the number the less sensitive the jabbing is. I am still working on this because it is hard to use. I am also going to add a gaming mode because for gaming you only want the mouse to move about 100 pictures. (Sorry for the bad hand writing on the picture I can not for my life draw with a mouse.)

**Comment by catvec** [comment]
![Capture](https://f.cloud.github.com/assets/3323504/96297/7d142b9a-669f-11e2-8051-a10fc2597211.PNG)
